// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: finance.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionEvaluator_AuditTransaction_FullMethodName = "/finance.TransactionEvaluator/AuditTransaction"
)

// TransactionEvaluatorClient is the client API for TransactionEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionEvaluatorClient interface {
	AuditTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type transactionEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionEvaluatorClient(cc grpc.ClientConnInterface) TransactionEvaluatorClient {
	return &transactionEvaluatorClient{cc}
}

func (c *transactionEvaluatorClient) AuditTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, TransactionEvaluator_AuditTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionEvaluatorServer is the server API for TransactionEvaluator service.
// All implementations must embed UnimplementedTransactionEvaluatorServer
// for forward compatibility.
type TransactionEvaluatorServer interface {
	AuditTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	mustEmbedUnimplementedTransactionEvaluatorServer()
}

// UnimplementedTransactionEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionEvaluatorServer struct{}

func (UnimplementedTransactionEvaluatorServer) AuditTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditTransaction not implemented")
}
func (UnimplementedTransactionEvaluatorServer) mustEmbedUnimplementedTransactionEvaluatorServer() {}
func (UnimplementedTransactionEvaluatorServer) testEmbeddedByValue()                              {}

// UnsafeTransactionEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionEvaluatorServer will
// result in compilation errors.
type UnsafeTransactionEvaluatorServer interface {
	mustEmbedUnimplementedTransactionEvaluatorServer()
}

func RegisterTransactionEvaluatorServer(s grpc.ServiceRegistrar, srv TransactionEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedTransactionEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionEvaluator_ServiceDesc, srv)
}

func _TransactionEvaluator_AuditTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionEvaluatorServer).AuditTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionEvaluator_AuditTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionEvaluatorServer).AuditTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionEvaluator_ServiceDesc is the grpc.ServiceDesc for TransactionEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.TransactionEvaluator",
	HandlerType: (*TransactionEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuditTransaction",
			Handler:    _TransactionEvaluator_AuditTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance.proto",
}
