// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: finance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OrganizationCnpj string                 `protobuf:"bytes,2,opt,name=organization_cnpj,json=organizationCnpj,proto3" json:"organization_cnpj,omitempty"`
	MonetaryValue    float64                `protobuf:"fixed64,3,opt,name=monetary_value,json=monetaryValue,proto3" json:"monetary_value,omitempty"`
	EncryptedPayload string                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRequest) GetOrganizationCnpj() string {
	if x != nil {
		return x.OrganizationCnpj
	}
	return ""
}

func (x *TransactionRequest) GetMonetaryValue() float64 {
	if x != nil {
		return x.MonetaryValue
	}
	return 0
}

func (x *TransactionRequest) GetEncryptedPayload() string {
	if x != nil {
		return x.EncryptedPayload
	}
	return ""
}

type TransactionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TransactionId       string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	IsApproved          bool                   `protobuf:"varint,2,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	ComplianceStatus    string                 `protobuf:"bytes,3,opt,name=compliance_status,json=complianceStatus,proto3" json:"compliance_status,omitempty"`
	LatencyMicroseconds int64                  `protobuf:"varint,4,opt,name=latency_microseconds,json=latencyMicroseconds,proto3" json:"latency_microseconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *TransactionResponse) GetComplianceStatus() string {
	if x != nil {
		return x.ComplianceStatus
	}
	return ""
}

func (x *TransactionResponse) GetLatencyMicroseconds() int64 {
	if x != nil {
		return x.LatencyMicroseconds
	}
	return 0
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\"\xbc\x01\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12+\n" +
	"\x11organization_cnpj\x18\x02 \x01(\tR\x10organizationCnpj\x12%\n" +
	"\x0emonetary_value\x18\x03 \x01(\x01R\rmonetaryValue\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\tR\x10encryptedPayload\"\xbd\x01\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vis_approved\x18\x02 \x01(\bR\n" +
	"isApproved\x12+\n" +
	"\x11compliance_status\x18\x03 \x01(\tR\x10complianceStatus\x121\n" +
	"\x14latency_microseconds\x18\x04 \x01(\x03R\x13latencyMicroseconds2e\n" +
	"\x14TransactionEvaluator\x12M\n" +
	"\x10AuditTransaction\x12\x1b.finance.TransactionRequest\x1a\x1c.finance.TransactionResponseB\x1cZ\x1aservice-processor-go/pb;pbb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_finance_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: finance.TransactionRequest
	(*TransactionResponse)(nil), // 1: finance.TransactionResponse
}
var file_finance_proto_depIdxs = []int32{
	0, // 0: finance.TransactionEvaluator.AuditTransaction:input_type -> finance.TransactionRequest
	1, // 1: finance.TransactionEvaluator.AuditTransaction:output_type -> finance.TransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
